package com.basir.ai;

import android.content.ContentResolver;
import android.content.Context;
import android.content.SharedPreferences;
import android.net.Uri;
import android.util.Base64;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;

/**
 * AiClient: high-level dispatcher.
 *
 *   - "proxy"  mode: talk to the Basir Node.js proxy server (which holds the Gemini key).
 *   - "direct" mode: talk to Google's Gemini API directly from the device.
 *
 * Settings live in SharedPreferences under:
 *   ai_mode            = "direct" | "proxy"   (default "proxy")
 *   ai_server_url      = base URL of the proxy (only used in proxy mode)
 *   ai_app_token       = optional shared secret with the proxy
 *   gemini_api_key     = Google AI Studio key (only used in direct mode)
 *   gemini_model_fast  = override for the flash model (optional)
 *   gemini_model_pro   = override for the pro model (optional)
 */
public final class AiClient {

    public static final String MODE_PROXY  = "proxy";
    public static final String MODE_DIRECT = "direct";

    private AiClient() {}

    // ---------------- configuration helpers ----------------

    public static String getMode(SharedPreferences prefs) {
        String mode = prefs.getString("ai_mode", MODE_PROXY);
        return MODE_DIRECT.equals(mode) ? MODE_DIRECT : MODE_PROXY;
    }

    public static boolean isConfigured(SharedPreferences prefs) {
        if (MODE_DIRECT.equals(getMode(prefs))) {
            String key = prefs.getString("gemini_api_key", "").trim();
            return !key.isEmpty();
        }
        String url = prefs.getString("ai_server_url", "").trim();
        return url.startsWith("http://") || url.startsWith("https://");
    }

    public static String pickModel(SharedPreferences prefs, String task) {
        boolean fast = "ask".equals(task) || "translate".equals(task)
                    || "reply".equals(task) || "quick".equals(task) || "health".equals(task);
        if (fast) {
            return prefs.getString("gemini_model_fast", GeminiDirectClient.DEFAULT_FLASH).trim();
        }
        return prefs.getString("gemini_model_pro", GeminiDirectClient.DEFAULT_PRO).trim();
    }

    // ---------------- public API ----------------

    public static String ask(SharedPreferences prefs, String task,
                             String input, String instruction, String language) throws Exception {
        return ask(prefs, task, input, instruction, language, null, null);
    }

    public static String ask(SharedPreferences prefs, String task,
                             String input, String instruction, String language,
                             String imageBase64, String mimeType) throws Exception {
        if (MODE_DIRECT.equals(getMode(prefs))) {
            String key = prefs.getString("gemini_api_key", "");
            String model = pickModel(prefs, task);
            String systemText = systemPrompt(language, instruction);
            return GeminiDirectClient.generateText(key, model, systemText, input, imageBase64, mimeType);
        }
        return proxyAsk(prefs, task, input, instruction, language, imageBase64, mimeType);
    }

    /**
     * Convert a PDF or PPTX file to a .docx, with image / table descriptions
     * generated by Gemini. Works in both modes.
     */
    public static String convertToDocx(Context ctx, SharedPreferences prefs, Uri sourceUri,
                                       String mode, String language, File outFile) throws Exception {
        if (MODE_DIRECT.equals(getMode(prefs))) {
            return directConvertToDocx(ctx, prefs, sourceUri, mode, language, outFile);
        }
        return proxyConvertToDocx(ctx, prefs, sourceUri, mode, language, outFile);
    }

    // ============================================================
    //                      PROXY IMPLEMENTATION
    // ============================================================

    private static String chatEndpoint(String baseUrl) {
        String u = baseUrl.trim();
        if (u.endsWith("/api/basir") || u.endsWith("/api/basir/")) return u;
        if (u.endsWith("/")) return u + "api/basir";
        return u + "/api/basir";
    }

    private static String convertEndpoint(String baseUrl) {
        String u = baseUrl.trim();
        if (u.endsWith("/api/basir")) u = u.substring(0, u.length() - "/api/basir".length());
        if (u.endsWith("/api/basir/")) u = u.substring(0, u.length() - "/api/basir/".length());
        if (u.endsWith("/")) u = u.substring(0, u.length() - 1);
        return u + "/api/convert";
    }

    private static String proxyAsk(SharedPreferences prefs, String task,
                                   String input, String instruction, String language,
                                   String imageBase64, String mimeType) throws Exception {
        String baseUrl = prefs.getString("ai_server_url", "");
        String appToken = prefs.getString("ai_app_token", "");
        if (baseUrl.trim().isEmpty()) throw new Exception("Proxy URL is empty");

        JSONObject body = new JSONObject();
        body.put("task", task == null ? "ask" : task);
        body.put("input", input == null ? "" : input);
        body.put("instruction", instruction == null ? "" : instruction);
        body.put("language", language == null ? "ar" : language);
        if (imageBase64 != null && !imageBase64.trim().isEmpty()) {
            body.put("image_base64", imageBase64);
            body.put("mime_type", (mimeType == null || mimeType.trim().isEmpty()) ? "image/jpeg" : mimeType);
        }

        HttpURLConnection conn = (HttpURLConnection) new URL(chatEndpoint(baseUrl)).openConnection();
        conn.setRequestMethod("POST");
        conn.setConnectTimeout(30000);
        conn.setReadTimeout(120000);
        conn.setDoOutput(true);
        conn.setRequestProperty("Content-Type", "application/json; charset=utf-8");
        conn.setRequestProperty("Accept", "application/json");
        conn.setRequestProperty("User-Agent", "Basir-Android/1.0.2");
        if (!appToken.trim().isEmpty()) {
            conn.setRequestProperty("X-Basir-Client-Token", appToken.trim());
        }

        try (OutputStream os = conn.getOutputStream()) {
            os.write(body.toString().getBytes(StandardCharsets.UTF_8));
        }

        int code = conn.getResponseCode();
        InputStream stream = (code >= 200 && code < 300) ? conn.getInputStream() : conn.getErrorStream();
        String response = readAll(stream);

        if (code < 200 || code >= 300) {
            throw new Exception("HTTP " + code + ": " + truncate(response, 400));
        }
        try {
            JSONObject json = new JSONObject(response);
            if (json.has("answer")) return json.getString("answer");
            if (json.has("error")) throw new Exception(json.getString("error"));
            return response;
        } catch (Exception parseErr) {
            return response;
        }
    }

    private static String proxyConvertToDocx(Context ctx, SharedPreferences prefs, Uri sourceUri,
                                             String mode, String language, File outFile) throws Exception {
        String baseUrl = prefs.getString("ai_server_url", "");
        String appToken = prefs.getString("ai_app_token", "");
        if (baseUrl.trim().isEmpty()) throw new Exception("Proxy URL is empty");

        String boundary = "----BasirBoundary" + System.currentTimeMillis();
        ContentResolver resolver = ctx.getContentResolver();
        String mime = resolver.getType(sourceUri);
        if (mime == null) mime = "application/octet-stream";
        String filename = "document";
        if (mime.contains("pdf")) filename = "document.pdf";
        else if (mime.contains("presentation")) filename = "document.pptx";

        HttpURLConnection conn = (HttpURLConnection) new URL(convertEndpoint(baseUrl)).openConnection();
        conn.setRequestMethod("POST");
        conn.setConnectTimeout(30000);
        conn.setReadTimeout(300000);
        conn.setDoOutput(true);
        conn.setRequestProperty("Content-Type", "multipart/form-data; boundary=" + boundary);
        conn.setRequestProperty("User-Agent", "Basir-Android/1.0.2");
        if (!appToken.trim().isEmpty()) {
            conn.setRequestProperty("X-Basir-Client-Token", appToken.trim());
        }

        try (DataOutputStream out = new DataOutputStream(conn.getOutputStream())) {
            writeFormField(out, boundary, "language", language == null ? "ar" : language);
            writeFormField(out, boundary, "mode", mode == null ? "full" : mode);
            out.writeBytes("--" + boundary + "\r\n");
            out.writeBytes("Content-Disposition: form-data; name=\"file\"; filename=\"" + filename + "\"\r\n");
            out.writeBytes("Content-Type: " + mime + "\r\n\r\n");
            try (InputStream in = resolver.openInputStream(sourceUri)) {
                if (in == null) throw new Exception("Could not open the chosen file");
                byte[] buf = new byte[8192];
                int n;
                while ((n = in.read(buf)) != -1) out.write(buf, 0, n);
            }
            out.writeBytes("\r\n");
            out.writeBytes("--" + boundary + "--\r\n");
        }

        int code = conn.getResponseCode();
        if (code < 200 || code >= 300) {
            String err = readAll(conn.getErrorStream());
            throw new Exception("HTTP " + code + ": " + truncate(err, 400));
        }

        try (InputStream in = conn.getInputStream();
             FileOutputStream fos = new FileOutputStream(outFile)) {
            byte[] buf = new byte[8192];
            int n;
            while ((n = in.read(buf)) != -1) fos.write(buf, 0, n);
        }
        return outFile.getAbsolutePath();
    }

    // ============================================================
    //                      DIRECT IMPLEMENTATION
    // ============================================================

    private static String directConvertToDocx(Context ctx, SharedPreferences prefs, Uri sourceUri,
                                              String mode, String language, File outFile) throws Exception {
        String key = prefs.getString("gemini_api_key", "");
        String model = pickModel(prefs, "convert");
        String mimeType = ctx.getContentResolver().getType(sourceUri);
        if (mimeType == null) mimeType = "application/octet-stream";

        boolean isPdf = mimeType.contains("pdf");
        boolean isPptx = mimeType.contains("presentation");

        if (isPptx) {
            return directConvertPptx(ctx, sourceUri, key, model, mode, language, outFile);
        }
        // PDF (or fall-through generic) - send the raw bytes inline.
        byte[] bytes = readUriBytesRaw(ctx, sourceUri, 25 * 1024 * 1024);
        String langName = (language != null && language.toLowerCase().startsWith("ar")) ? "Arabic" : "English";
        String prompt = buildDocPrompt(langName, mode);

        JSONObject parsed = GeminiDirectClient.generateJsonWithFile(
                key, model,
                "You are Basir, an assistant for blind and low-vision users.",
                prompt, bytes, isPdf ? "application/pdf" : mimeType);

        renderDocxFromJson(parsed, language, outFile);
        return outFile.getAbsolutePath();
    }

    private static String directConvertPptx(Context ctx, Uri sourceUri, String apiKey, String model,
                                            String mode, String language, File outFile) throws Exception {
        PptxExtractor.Deck deck = PptxExtractor.parse(ctx, sourceUri);
        if (deck.slides.isEmpty()) throw new Exception("No readable slides found");

        boolean arabic = language != null && language.toLowerCase().startsWith("ar");
        String langName = arabic ? "Arabic" : "English";

        DocxBuilder doc = new DocxBuilder(arabic ? "ar" : "en");
        doc.title(arabic ? "تحويل عرض تقديمي" : "Presentation conversion");

        // Process each slide separately so very large decks still succeed.
        for (PptxExtractor.Slide slide : deck.slides) {
            doc.heading(1, (arabic ? "الشريحة " : "Slide ") + slide.index);
            if (slide.text != null && !slide.text.isEmpty()) {
                doc.paragraph(slide.text);
            }

            if (!slide.images.isEmpty()) {
                // Build a single Gemini call containing all slide images.
                JSONArray parts = new JSONArray();
                String prompt =
                        "Describe each of the following images from a PowerPoint slide for a blind user. "
                      + "Respond strictly in " + langName + ". "
                      + "Return JSON: {\"images\":[{\"index\":1,\"description\":\"...\"}, ...]}. "
                      + "Describe type, main elements, text on the image, layout and purpose.";
                parts.put(new JSONObject().put("text", prompt));
                for (PptxExtractor.SlideMedia img : slide.images) {
                    JSONObject inline = new JSONObject();
                    inline.put("mimeType", img.mimeType);
                    inline.put("data", Base64.encodeToString(img.bytes, Base64.NO_WRAP));
                    parts.put(new JSONObject().put("inlineData", inline));
                }

                try {
                    JSONObject resp = GeminiDirectClient.generateJsonWithParts(
                            apiKey, model,
                            "You are Basir, an assistant for blind and low-vision users.",
                            parts);
                    JSONArray arr = resp.optJSONArray("images");
                    if (arr != null) {
                        for (int i = 0; i < arr.length(); i++) {
                            JSONObject im = arr.getJSONObject(i);
                            String desc = im.optString("description", "").trim();
                            if (!desc.isEmpty()) {
                                doc.heading(3, (arabic ? "وصف الصورة " : "Image description ")
                                              + im.optInt("index", i + 1));
                                doc.paragraph(desc);
                            }
                        }
                    }
                } catch (Exception ignored) {
                    // Skip image batch on error; keep generating the rest.
                    doc.paragraph(arabic
                            ? "(تعذر وصف الصور في هذه الشريحة.)"
                            : "(Could not describe the images on this slide.)");
                }
            }
        }
        doc.writeTo(outFile);
        return outFile.getAbsolutePath();
    }

    /** Build the structured-JSON prompt used for PDF conversion. */
    private static String buildDocPrompt(String langName, String mode) {
        String modeNote;
        switch (mode == null ? "full" : mode.toLowerCase()) {
            case "simple":
                modeNote = "Plain-text version optimized for screen readers; no decorative elements.";
                break;
            case "descriptions_only":
                modeNote = "Output ONLY image descriptions, one per heading.";
                break;
            case "text_only":
                modeNote = "Output ONLY extracted text and tables; skip image descriptions.";
                break;
            default:
                modeNote = "Include all text, tables, and detailed image descriptions.";
        }
        return  "You are processing a document for a blind user.\n"
              + "Respond strictly in " + langName + ".\n"
              + modeNote + "\n\n"
              + "Return a SINGLE JSON object (no markdown, no code fences) with this shape:\n"
              + "{\n"
              + "  \"title\": \"...\",\n"
              + "  \"summary\": \"short summary 1-3 sentences\",\n"
              + "  \"sections\": [\n"
              + "    { \"type\": \"page_marker\", \"label\": \"Page 1\" },\n"
              + "    { \"type\": \"heading\", \"level\": 1, \"text\": \"...\" },\n"
              + "    { \"type\": \"paragraph\", \"text\": \"...\" },\n"
              + "    { \"type\": \"image_description\", \"context\": \"Page 1\", \"description\": \"...\" },\n"
              + "    { \"type\": \"table_description\", \"rows\": 6, \"cols\": 4, \"context\": \"Page 2\", \"summary\": \"...\" }\n"
              + "  ]\n"
              + "}\n\n"
              + "Rules:\n"
              + "- Describe every image thoroughly (type, main elements, layout, visible text, purpose).\n"
              + "- For tables, give dimensions and a screen-reader friendly summary.\n"
              + "- Insert page_marker for each PDF page.\n"
              + "- Never identify real people by face.\n"
              + "- Output valid JSON only, no other prose.";
    }

    /** Render the JSON tree returned by Gemini into a .docx file. */
    private static void renderDocxFromJson(JSONObject parsed, String language, File outFile) throws Exception {
        boolean arabic = language != null && language.toLowerCase().startsWith("ar");
        DocxBuilder doc = new DocxBuilder(arabic ? "ar" : "en");

        String labelImg = arabic ? "وصف الصورة" : "Image description";
        String labelTbl = arabic ? "جدول"     : "Table";
        String labelPage = arabic ? "الصفحة"  : "Page";
        String labelSlide = arabic ? "الشريحة" : "Slide";

        String title = parsed.optString("title", "");
        if (!title.isEmpty()) doc.title(title);
        String summary = parsed.optString("summary", "");
        if (!summary.isEmpty()) doc.paragraph(summary);

        JSONArray sections = parsed.optJSONArray("sections");
        if (sections != null) {
            for (int i = 0; i < sections.length(); i++) {
                JSONObject sec = sections.optJSONObject(i);
                if (sec == null) continue;
                String type = sec.optString("type", "");
                switch (type) {
                    case "page_marker":
                        doc.heading(1, sec.optString("label", labelPage));
                        break;
                    case "slide_marker":
                        doc.heading(1, sec.optString("label", labelSlide));
                        break;
                    case "heading": {
                        int lvl = sec.optInt("level", 2);
                        doc.heading(lvl, sec.optString("text", ""));
                        break;
                    }
                    case "paragraph":
                        doc.paragraph(sec.optString("text", ""));
                        break;
                    case "image_description": {
                        String ctx = sec.optString("context", "");
                        String prefix = labelImg + (ctx.isEmpty() ? "" : " (" + ctx + ")") + ":";
                        doc.heading(3, prefix);
                        doc.paragraph(sec.optString("description", ""));
                        break;
                    }
                    case "table_description": {
                        int rows = sec.optInt("rows", 0);
                        int cols = sec.optInt("cols", 0);
                        String dims = (rows > 0 && cols > 0) ? " (" + rows + " × " + cols + ")" : "";
                        String ctx = sec.optString("context", "");
                        String prefix = labelTbl + dims + (ctx.isEmpty() ? "" : " (" + ctx + ")") + ":";
                        doc.heading(3, prefix);
                        doc.paragraph(sec.optString("summary", ""));
                        break;
                    }
                    default:
                        String fallback = sec.optString("text", "");
                        if (!fallback.isEmpty()) doc.paragraph(fallback);
                }
            }
        }
        doc.writeTo(outFile);
    }

    private static String systemPrompt(String language, String instruction) {
        String name = (language != null && language.toLowerCase().startsWith("ar")) ? "Arabic" : "English";
        StringBuilder sb = new StringBuilder();
        sb.append("You are Basir, an assistant for blind and low-vision users.\n");
        sb.append("Respond strictly in ").append(name).append(" unless the user explicitly asks otherwise.\n");
        sb.append("Be practical, structured, and screen-reader friendly.\n");
        sb.append("Never identify real persons by face.\n");
        sb.append("Avoid medical diagnosis or legal verdicts; suggest consulting a professional.\n");
        if (instruction != null && !instruction.trim().isEmpty()) sb.append(instruction);
        return sb.toString();
    }

    // ============================================================
    //                            UTILITIES
    // ============================================================

    public static byte[] readUriBytes(Context context, Uri uri, int maxBytes) throws Exception {
        return readUriBytesRaw(context, uri, maxBytes);
    }

    private static byte[] readUriBytesRaw(Context context, Uri uri, int maxBytes) throws Exception {
        ContentResolver resolver = context.getContentResolver();
        try (InputStream input = resolver.openInputStream(uri);
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            if (input == null) throw new Exception("Could not read the file stream");
            byte[] buffer = new byte[8192];
            int total = 0;
            int read;
            while ((read = input.read(buffer)) != -1) {
                total += read;
                if (total > maxBytes) throw new Exception("File larger than allowed limit");
                out.write(buffer, 0, read);
            }
            return out.toByteArray();
        }
    }

    public static String encodeBase64(byte[] data) {
        return Base64.encodeToString(data, Base64.NO_WRAP);
    }

    public static String detectMime(Context context, Uri uri) {
        String mime = context.getContentResolver().getType(uri);
        return (mime == null || mime.trim().isEmpty()) ? "image/jpeg" : mime;
    }

    private static void writeFormField(DataOutputStream out, String boundary,
                                       String name, String value) throws Exception {
        out.writeBytes("--" + boundary + "\r\n");
        out.writeBytes("Content-Disposition: form-data; name=\"" + name + "\"\r\n\r\n");
        out.write(value.getBytes(StandardCharsets.UTF_8));
        out.writeBytes("\r\n");
    }

    private static String readAll(InputStream stream) throws Exception {
        if (stream == null) return "";
        StringBuilder sb = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8))) {
            String line;
            while ((line = br.readLine()) != null) sb.append(line).append('\n');
        }
        return sb.toString().trim();
    }

    private static String truncate(String s, int max) {
        if (s == null) return "";
        return s.length() <= max ? s : s.substring(0, max) + "...";
    }
}
